import "./globals.css";
import Header from "../components/Header.js";
import Footer from "../components/Footer.js";
import localFont from "next/font/local";

const JetBrainsMono = localFont({
  src:
    [{
      path: "../fonts/JetBrainsMono-Regular.woff2",
      weight: "400"
    }],
    variable: "--font-JetBrainsMono"
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  >
      <body className={`${JetBrainsMono.variable} flex flex-col h-screen`}>
        <Header/>
	  <div className="flex-1">
          	{children}
	  </div> 
        <Footer />
      </body>
    </html>
  );
}
