
export const metadata = {
  title: "Blogs",
  description: "Generated by create next app",
};

export default function BlogLayout({ children }) {
  return(
	<section className={`font-JetBrainsMono text-white mt-10`}>
		<div className="md:w-1/2 md:mx-auto mx-4">
			{children}
		</div> 
	</section>
  )
}
