
export const metadata = {
  title: "Blogs",
  description: "Generated by create next app",
};

export default function BlogLayout({ children }) {
  return(
	<section className={`font-poppins text-[#F8F8FF] mt-10`}>
		<div className="mx-4">
			{children}
		</div> 
	</section>
  )
}
